-- CreateEnum
CREATE TYPE "Permission" AS ENUM ('VIEW_DASHBOARD', 'VIEW_MEMBERS', 'CREATE_MEMBERS', 'EDIT_MEMBERS', 'DELETE_MEMBERS', 'VIEW_BILLING', 'CREATE_PAYMENTS', 'EDIT_PAYMENTS', 'VIEW_INVOICES', 'CREATE_INVOICES', 'VIEW_WORKOUTS', 'CREATE_WORKOUTS', 'EDIT_WORKOUTS', 'DELETE_WORKOUTS', 'VIEW_DIETS', 'CREATE_DIETS', 'EDIT_DIETS', 'DELETE_DIETS', 'VIEW_ATTENDANCE', 'MARK_ATTENDANCE', 'VIEW_LEADS', 'CREATE_LEADS', 'EDIT_LEADS', 'VIEW_REPORTS', 'VIEW_STAFF', 'CREATE_STAFF', 'EDIT_STAFF', 'DELETE_STAFF', 'VIEW_SETTINGS', 'EDIT_SETTINGS');

-- AlterEnum
ALTER TYPE "UserRole" ADD VALUE 'HELPER';

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "permissions" "Permission"[];
